version: '3.5'

services:
  api:
    container_name: api
    # command: "npm run prod"
    image: barlima/rate-that-bridge-api
    # environment:
      # NODE_ENV: production
    ports:
      - '4000:4000'
    volumes: 
      - './api/database.sqlite:/usr/src/app/database.sqlite'
      - './api/src:/usr/src/app/src'
  app:
    container_name: app
    image: barlima/rate-that-bridge-app
    ports:
      - '3000:3000'
    links:
      - api
  server:
    container_name: server
    image: nginx:latest
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - api
    ports:
      - '80:80'
      - '443:443'
