version: '3.5'

services:
  api:
    command: yarn start
    environment:
      NODE_ENV: development
    volumes: 
      - './api/database.sqlite:/usr/src/app/database.sqlite'
      - './api/src:/usr/src/app/src'
  app:
    command: yarn start
    environment:
      NODE_ENV: development
    volumes:
      - './app/src:/usr/src/app/src'