version: '3.5'

services:
  api:
    container_name: api
    image: barlima/rate-that-bridge-api
    environment:
      NODE_ENV: production
    env_file:
      - '.env'
    volumes: 
      - './api/database.sqlite:/usr/src/app/database.sqlite'
    ports:
      - '4000:4000'
  app:
    container_name: app
    image: barlima/rate-that-bridge-app
    environment:
      NODE_ENV: production
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    links:
      - api
  server:
    container_name: server
    image: nginx:latest
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - api
    ports:
      - '80:80'
      - '443:443'
