version: '3.5'

services:
  sqlite:
    container_name: sqlite
    image: nouchka/sqlite3
    stdin_open: true
    tty: true
    volumes:
      - db:/root/db/
    ports: 
      - '3333:3333'
  api:
    container_name: api
    image: barlima/rate-that-bridge-api
    environment:
      NODE_ENV: production
    ports:
      - '4000:4000'
    depends_on:
      - sqlite
  app:
    container_name: app
    image: barlima/rate-that-bridge-app
    ports:
      - '3000:3000'
    links:
      - api
  server:
    container_name: server
    image: nginx:latest
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - api
    ports:
      - '80:80'
      - '443:443'
  volumes: 
    db: